"""empty message

Revision ID: cfff8c7ef316
Revises: None
Create Date: 2016-04-28 22:56:49.204862

"""

# revision identifiers, used by Alembic.
revision = 'cfff8c7ef316'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('default', sa.Boolean(), nullable=True))
    op.add_column('roles', sa.Column('perssions', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_column('roles', 'perssions')
    op.drop_column('roles', 'default')
    ### end Alembic commands ###
