"""empty message

Revision ID: fc9e163f10ae
Revises: 52b6d2e68ac0
Create Date: 2016-05-16 22:48:41.527468

"""

# revision identifiers, used by Alembic.
revision = 'fc9e163f10ae'
down_revision = '52b6d2e68ac0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
